// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package bootstrap

import (
	"github.com/kainonly/countries-states-cities-mongo/api"
	"github.com/kainonly/countries-states-cities-mongo/common"
)

// Injectors from wire.go:

func NewAPI() (*api.API, error) {
	values, err := LoadValues()
	if err != nil {
		return nil, err
	}
	client, err := UseMongoDB(values)
	if err != nil {
		return nil, err
	}
	database := UseDatabase(client, values)
	inject := &common.Inject{
		Values:      values,
		MongoClient: client,
		Db:          database,
	}
	apiAPI := &api.API{
		Inject: inject,
	}
	return apiAPI, nil
}
