// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"countries-states-cities-mongo/app"
	"countries-states-cities-mongo/bootstrap"
	"countries-states-cities-mongo/common"
)

// Injectors from wire.go:

func App(value *common.Values) (*app.App, error) {
	client, err := bootstrap.UseMongoDB(value)
	if err != nil {
		return nil, err
	}
	database := bootstrap.UseDatabase(client, value)
	inject := &common.Inject{
		Values:      value,
		MongoClient: client,
		Db:          database,
	}
	appApp := app.New(inject)
	return appApp, nil
}
